/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jnisample_JNIHelloWorld_JNIActivity */

#ifndef _Included_com_ros_sampleapp_sampleApp
#define _Included_com_ros_sampleapp_sampleApp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jnisample_JNIHelloWorld_JNIActivity
 * Method:    getNativeMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT void JNICALL Java_com_ros_sampleapp_sampleApp_changeStopStart
  (JNIEnv *, jobject,jint);
JNIEXPORT void JNICALL Java_com_ros_sampleapp_sampleApp_init
  (JNIEnv *, jobject);
JNIEXPORT void JNICALL Java_com_ros_sampleapp_sampleApp_changeSpeed
  (JNIEnv *, jobject,jint);
JNIEXPORT void JNICALL Java_com_ros_sampleapp_sampleApp_changeSteering
  (JNIEnv *, jobject,jint);


#ifdef __cplusplus
}
#endif
#endif